import re

with open("src/pyacemaker/core/lammps_generator.py", "r") as f:
    content = f.read()

target = '        buffer.write("compute max_gamma all reduce max c_gamma\\n")'

# The spec says:
# "Ensure the integer tags generated by the spatial module are properly propagated to the `TwoTierEvaluatorConfig` within the compiler. The compiler must automatically configure the active learning evaluator to explicitly ignore MACE uncertainty variance scores for any atoms assigned the `ACTION_FREEZE` tag. This logic optimizes the active learning loop's computational speed by instructing the GPU to completely skip variance evaluation for geometry that is physically constrained from moving, saving significant execution time over millions of MD steps."
# "instructing the GPU to completely skip variance evaluation" means the LAMMPS `compute` should only run on a specific group!
# We can dynamically define an active_atoms group that is "all subtract freeze_group" and run `compute gamma active_atoms pace ...`.

# Let's change `_gen_watchdog` to use `active_atoms` if freezing commands exist, or just use `all`.
# Wait, if we use `active_atoms`, the generator needs to know if any atoms are frozen. We could parse the custom commands or just use `all` unless `ignored_atoms` is present in `workflow_config`. But `MDConfig` doesn't know about `WorkflowConfig`.
# Actually, if we just define `active_atoms` at the end of custom initialization:
# `group active_atoms subtract all <freeze_groups>`
# Then we can just use `active_atoms` if it exists. But LAMMPS will error if `active_atoms` isn't defined.
# Let's check if the string "active_atoms" is in the custom commands. No.
# Instead, the semantic compiler can just add `group active_atoms union all` or similar.
# Wait, if `MDConfig` has `ignored_atoms` we could use it, but it's in `LoopStrategyConfig.thresholds`.

# Let's just do it in python evaluation: The GPU still evaluates it for all atoms if the compute uses `all`.
# Wait, the spec explicitly says: "by instructing the GPU to completely skip variance evaluation for geometry that is physically constrained from moving, saving significant execution time over millions of MD steps."
# This means `compute gamma` MUST use a group.
# How do we pass the group to `_gen_watchdog`?
# In `compiler.py`, we generated `group group_{i}` and `fix freeze_...`. We can also append: `group freeze_atoms union group_{i}` for all freeze groups.
# Then `group active_atoms subtract all freeze_atoms`.
# Then `compute gamma active_atoms pace ...`.
# Let's modify `compiler.py` to add those LAMMPS commands.

import os
with open("src/pyacemaker/domain_models/compiler.py", "r") as f:
    compiler_code = f.read()

# Modify `_apply_spatial_logic` in compiler.py to generate active_atoms group
compiler_replacement = """        for i, region in enumerate(regions):
            tag_value = i + 1
            group_name = f"group_{tag_value}"

            if region.action == PhysicalAction.ACTION_FREEZE:
                cmds.append(f"fix freeze_fix_{tag_value} {group_name} setforce 0.0 0.0 0.0")
                cmds.append(f"group freeze_atoms union {group_name}")
                indices = np.where(tags == tag_value)[0] + 1
                freeze_indices.extend(indices.tolist())

        if freeze_indices:
            cmds.append("group active_atoms subtract all freeze_atoms")
        else:
            cmds.append("group active_atoms union all")

        md_config.custom_initialization_commands = cmds
"""

compiler_code = re.sub(
    r"        for i, region in enumerate\(regions\):\n            tag_value = i \+ 1\n            group_name = f\"group_\{tag_value\}\"\n\n            if region\.action == PhysicalAction\.ACTION_FREEZE:\n                cmds\.append\(f\"fix freeze_fix_\{tag_value\} \{group_name\} setforce 0\.0 0\.0 0\.0\"\)\n                indices = np\.where\(tags == tag_value\)\[0\] \+ 1\n                freeze_indices\.extend\(indices\.tolist\(\)\)\n\n        md_config\.custom_initialization_commands = cmds",
    compiler_replacement,
    compiler_code
)

with open("src/pyacemaker/domain_models/compiler.py", "w") as f:
    f.write(compiler_code)
