backend:
  batch_size: 10
  display_step: 50
  evaluator: tensorpot
cutoff: 5.0
data:
  filename: /app/tutorials/uat_output/active_learning/iter_000/training/training_data.xyz
fit:
  loss:
    L1_coeffs: 1.0e-08
    L2_coeffs: 1.0e-08
    kappa: 0.3
  maxiter: 1000
  optimizer: BFGS
  repulsion_sigma: 0.05
potential:
  bonds:
    N: 500
    max_deg: 6
    r0: 1.5
    rad_base: Chebyshev
    rad_parameters:
    - 1.0
  delta_spline_bins: 100
  elements:
  - Mg
  - O
  embeddings:
    Mg:
      fs_parameters: &id001
      - 1.0
      - 1.0
      - 1.0
      - 1.5
      maxwell: true
      ndensity: 2
      npot: FinnisSinclair
    O:
      fs_parameters: *id001
      maxwell: true
      ndensity: 2
      npot: FinnisSinclair
seed: 42
