import json
import os
from typing import Any, Final

DANGEROUS_PATH_CHARS: Final[set[str]] = {
    ";",
    "&",
    "|",
    "`",
    "$",
    "(",
    ")",
    "<",
    ">",
    "\n",
    "\r",
    "\t",
    "?",
    "*",
    "[",
    "]",
    "{",
    "}",
    "'",
    '"',
    "!",
    "#",
}

DEFAULT_PROJECT_NAME: Final[str] = os.getenv("PYACEMAKER_PROJECT_NAME", "intent_driven_project")
DEFAULT_SLIDER_MIN: Final[int] = int(os.getenv("PYACEMAKER_SLIDER_MIN", "1"))
DEFAULT_SLIDER_MAX: Final[int] = int(os.getenv("PYACEMAKER_SLIDER_MAX", "10"))
DEFAULT_MAX_ITERATIONS: Final[int] = int(os.getenv("PYACEMAKER_MAX_ITERATIONS", "10"))
DEFAULT_BATCH_SIZE: Final[int] = int(os.getenv("PYACEMAKER_BATCH_SIZE", "5"))
DEFAULT_N_CANDIDATES: Final[int] = int(os.getenv("PYACEMAKER_N_CANDIDATES", "10"))

DEFAULT_MD_BASE_ENERGY: Final[float] = float(os.getenv("PYACEMAKER_MD_BASE_ENERGY", "-100.0"))
DEFAULT_PACEMAKER_LOSS_L1: Final[float] = float(os.getenv("PYACEMAKER_PACEMAKER_LOSS_L1", "1e-8"))
DEFAULT_PACEMAKER_LOSS_L2: Final[float] = float(os.getenv("PYACEMAKER_PACEMAKER_LOSS_L2", "1e-8"))
DEFAULT_PACEMAKER_REPULSION_SIGMA: Final[float] = float(
    os.getenv("PYACEMAKER_PACEMAKER_REPULSION_SIGMA", "0.05")
)
DEFAULT_PACEMAKER_RAD_BASE: Final[str] = os.getenv("PYACEMAKER_PACEMAKER_RAD_BASE", "Chebyshev")
DEFAULT_PACEMAKER_EMBEDDING_TYPE: Final[str] = os.getenv(
    "PYACEMAKER_PACEMAKER_EMBEDDING_TYPE", "FinnisSinclair"
)
DEFAULT_PACEMAKER_OPTIMIZER: Final[str] = os.getenv("PYACEMAKER_PACEMAKER_OPTIMIZER", "BFGS")

DEFAULT_SMEARING_TYPE: Final[str] = os.getenv("PYACEMAKER_SMEARING_TYPE", "gaussian")
DEFAULT_SMEARING_WIDTH: Final[float] = float(os.getenv("PYACEMAKER_SMEARING_WIDTH", "0.1"))
_default_smearing_fallbacks = '{"Pt": {"smearing_type": "mv", "smearing_width": 0.02}}'
ELEMENT_SMEARING_FALLBACKS: Final[dict[str, Any]] = json.loads(
    os.getenv("PYACEMAKER_ELEMENT_SMEARING_FALLBACKS", _default_smearing_fallbacks)
)

ACTION_PRIORITY: dict[str, int] = {
    "ACTION_ACTIVE_LEARNING_ONLY": 1,
    "ACTION_LANGEVIN_THERMOSTAT": 2,
    "ACTION_FREEZE": 3,
}

DEFAULT_TAG_ASSIGNMENT_STRATEGY: Final[str] = os.getenv(
    "PYACEMAKER_TAG_ASSIGNMENT_STRATEGY", "priority"
)

_default_pseudo_mapping = '{"Al": "Al.pbe-n-kjpaw_psl.1.0.0.UPF", "W": "W.pbe-n-kjpaw_psl.1.0.0.UPF", "H": "H.pbe-rrkjus_psl.1.0.0.UPF", "O": "O.pbe-n-kjpaw_psl.0.1.UPF", "Pt": "Pt.pbe-n-kjpaw_psl.1.0.0.UPF", "Fe": "Fe.pbe-n-kjpaw_psl.1.0.0.UPF"}'
DEFAULT_PSEUDOPOTENTIAL_MAPPING: Final[dict[str, str]] = json.loads(
    os.getenv("PYACEMAKER_PSEUDOPOTENTIAL_MAPPING", _default_pseudo_mapping)
)

DEFAULT_ENCUT_BASE: Final[float] = float(os.getenv("PYACEMAKER_ENCUT_BASE", "40.0"))
DEFAULT_ENCUT_FACTOR: Final[float] = float(os.getenv("PYACEMAKER_ENCUT_FACTOR", "2.0"))
DEFAULT_KPOINTS_DENSITY_BASE: Final[float] = float(
    os.getenv("PYACEMAKER_KPOINTS_DENSITY_BASE", "2.0")
)
DEFAULT_KPOINTS_DENSITY_FACTOR: Final[float] = float(
    os.getenv("PYACEMAKER_KPOINTS_DENSITY_FACTOR", "4.0")
)
DEFAULT_DFT_FUNCTIONAL: Final[str] = os.getenv("PYACEMAKER_DFT_FUNCTIONAL", "pbe")
DEFAULT_DFT_CODE: Final[str] = os.getenv("PYACEMAKER_DFT_CODE", "quantum_espresso")

DEFAULT_DELTA_SPLINE_BINS: Final[int] = int(os.getenv("PYACEMAKER_DELTA_SPLINE_BINS", "100"))
DEFAULT_EVALUATOR: Final[str] = os.getenv("PYACEMAKER_EVALUATOR", "tensorpot")
DEFAULT_DISPLAY_STEP: Final[int] = int(os.getenv("PYACEMAKER_DISPLAY_STEP", "50"))
DEFAULT_PACEMAKER_LOSS_KAPPA: Final[float] = float(
    os.getenv("PYACEMAKER_PACEMAKER_LOSS_KAPPA", "0.3")
)
DEFAULT_PACEMAKER_MAX_DEG: Final[int] = int(os.getenv("PYACEMAKER_PACEMAKER_MAX_DEG", "6"))
DEFAULT_PACEMAKER_NDENSITY: Final[int] = int(os.getenv("PYACEMAKER_PACEMAKER_NDENSITY", "2"))
DEFAULT_PACEMAKER_R0: Final[float] = float(os.getenv("PYACEMAKER_PACEMAKER_R0", "1.5"))
DEFAULT_TRAINING_BATCH_SIZE: Final[int] = int(os.getenv("PYACEMAKER_TRAINING_BATCH_SIZE", "10"))
DEFAULT_TRAINING_MAX_ITERATIONS: Final[int] = int(
    os.getenv("PYACEMAKER_TRAINING_MAX_ITERATIONS", "1000")
)
FILENAME_POTENTIAL: Final[str] = os.getenv("PYACEMAKER_FILENAME_POTENTIAL", "potential.yace")
DEFAULT_EON_SEED: Final[int] = int(os.getenv("PYACEMAKER_EON_SEED", "12345"))
DEFAULT_LANGEVIN_SEED: Final[int] = int(os.getenv("PYACEMAKER_LANGEVIN_SEED", "12345"))
DEFAULT_MC_SEED: Final[int] = int(os.getenv("PYACEMAKER_MC_SEED", "12345"))


from .defaults import (  # noqa: E402
    DEFAULT_EON_EXECUTABLE,
    DEFAULT_LAMMPS_MINIMIZE_MAX_ITER,
    DEFAULT_LAMMPS_MINIMIZE_STEPS,
    DEFAULT_LAMMPS_VELOCITY_SEED,
    DEFAULT_LJ_PARAMS,
    DEFAULT_MD_MINIMIZE_FTOL,
    DEFAULT_MD_MINIMIZE_TOL,
    DEFAULT_RAM_DISK_PATH,
    DEFAULT_STRAIN_RANGE,
    EMBEDDING_TOLERANCE_CELL,
    ERR_GEN_BASE_FAIL,
    ERR_GEN_NCAND_NEG,
    ERR_M3GNET_PRED_FAIL,
    ERR_ORACLE_FAILED,
    ERR_ORACLE_ITERATOR,
    ERR_ORACLE_WARN_EMPTY,
    ERR_POTENTIAL_NOT_FOUND,
    ERR_SIM_EXEC_FAIL,
    ERR_SIM_SECURITY_FAIL,
    ERR_SIM_SETUP_FAIL,
    ERR_SIM_UNEXPECTED,
    ERR_STRUCTURE_NONE,
    ERR_VAL_POT_NONE,
    ERR_VAL_POT_NOT_FILE,
    ERR_VAL_POT_OUTSIDE,
    ERR_VAL_REQ_STRUCT,
    ERR_VAL_STRUCT_DUMMY_ELEM,
    ERR_VAL_STRUCT_EMPTY,
    ERR_VAL_STRUCT_NAN_POS,
    ERR_VAL_STRUCT_NONE,
    ERR_VAL_STRUCT_TYPE,
    ERR_VAL_STRUCT_UNKNOWN_SYM,
    ERR_VAL_STRUCT_VOL_FAIL,
    ERR_VAL_STRUCT_ZERO_VOL,
    FALLBACK_LJ_PARAMS,
    LAMMPS_MIN_STYLE_CG,
    LAMMPS_SAFE_CMD_PATTERN,
    LAMMPS_SCREEN_ARG,
    MAX_MD_DURATION,
    MAX_MD_PRESSURE,
    PACE_DRIVER_TEMPLATE,
    RECIPROCAL_FACTOR,
)

# Strategy Constants
STRATEGY_RATTLE_STDEV_INCREASE_FACTOR: Final[float] = 1.1
STRATEGY_RATTLE_STDEV_DECREASE_FACTOR: Final[float] = 0.95
STRATEGY_RATTLE_STDEV_MAX: Final[float] = 0.5
STRATEGY_RATTLE_STDEV_MIN: Final[float] = 0.05

# Policy Constants
POLICY_MICROBURST_N_STEPS: Final[int] = 100
POLICY_MICROBURST_NOISE_STDEV: Final[float] = 0.1
POLICY_NORMALMODE_NOISE_STDEV: Final[float] = 0.05

# Scenario Constants
SCENARIO_NAME_FEPT_MGO: Final[str] = "fept_mgo"
FILE_EXT_XYZ: Final[str] = "xyz"
FILE_EXT_EON_POS: Final[str] = "eon"
FILE_EXT_EXTXYZ: Final[str] = "extxyz"
FILE_NAME_MGO_SURFACE: Final[str] = "mgo_surface.xyz"
FILE_NAME_DEPOSITED: Final[str] = "deposited.xyz"
FILE_NAME_EON_POS: Final[str] = "pos.con"

__all__ = [
    "ACTION_PRIORITY",
    "BYTES_PER_ATOMIC_NUMBER",
    "BYTES_PER_FLOAT64",
    "DANGEROUS_PATH_CHARS",
    "DEFAULT_BATCH_SIZE",
    "DEFAULT_DELTA_SPLINE_BINS",
    "DEFAULT_DFT_CODE",
    "DEFAULT_DFT_FUNCTIONAL",
    "DEFAULT_DISPLAY_STEP",
    "DEFAULT_ENCUT_BASE",
    "DEFAULT_ENCUT_FACTOR",
    "DEFAULT_EON_EXECUTABLE",
    "DEFAULT_EON_SEED",
    "DEFAULT_EVALUATOR",
    "DEFAULT_KPOINTS_DENSITY_BASE",
    "DEFAULT_KPOINTS_DENSITY_FACTOR",
    "DEFAULT_LAMMPS_MINIMIZE_MAX_ITER",
    "DEFAULT_LAMMPS_MINIMIZE_STEPS",
    "DEFAULT_LAMMPS_VELOCITY_SEED",
    "DEFAULT_LJ_PARAMS",
    "DEFAULT_MAX_ITERATIONS",
    "DEFAULT_MC_SEED",
    "DEFAULT_MD_BASE_ENERGY",
    "DEFAULT_MD_MINIMIZE_FTOL",
    "DEFAULT_MD_MINIMIZE_TOL",
    "DEFAULT_N_CANDIDATES",
    "DEFAULT_PACEMAKER_EMBEDDING_TYPE",
    "DEFAULT_PACEMAKER_LOSS_KAPPA",
    "DEFAULT_PACEMAKER_LOSS_L1",
    "DEFAULT_PACEMAKER_LOSS_L2",
    "DEFAULT_PACEMAKER_MAX_DEG",
    "DEFAULT_PACEMAKER_NDENSITY",
    "DEFAULT_PACEMAKER_OPTIMIZER",
    "DEFAULT_PACEMAKER_R0",
    "DEFAULT_PACEMAKER_RAD_BASE",
    "DEFAULT_PACEMAKER_REPULSION_SIGMA",
    "DEFAULT_PROJECT_NAME",
    "DEFAULT_PSEUDOPOTENTIAL_MAPPING",
    "DEFAULT_RAM_DISK_PATH",
    "DEFAULT_SLIDER_MAX",
    "DEFAULT_SLIDER_MIN",
    "DEFAULT_SMEARING_TYPE",
    "DEFAULT_SMEARING_WIDTH",
    "DEFAULT_STRAIN_RANGE",
    "DEFAULT_TAG_ASSIGNMENT_STRATEGY",
    "DEFAULT_TRAINING_BATCH_SIZE",
    "DEFAULT_TRAINING_MAX_ITERATIONS",
    "ELEMENT_SMEARING_FALLBACKS",
    "EMBEDDING_TOLERANCE_CELL",
    "ERR_GEN_BASE_FAIL",
    "ERR_GEN_NCAND_NEG",
    "ERR_M3GNET_PRED_FAIL",
    "ERR_ORACLE_FAILED",
    "ERR_ORACLE_ITERATOR",
    "ERR_ORACLE_WARN_EMPTY",
    "ERR_POTENTIAL_NOT_FOUND",
    "ERR_SIM_EXEC_FAIL",
    "ERR_SIM_SECURITY_FAIL",
    "ERR_SIM_SETUP_FAIL",
    "ERR_SIM_UNEXPECTED",
    "ERR_STRUCTURE_NONE",
    "ERR_VAL_POT_NONE",
    "ERR_VAL_POT_NOT_FILE",
    "ERR_VAL_POT_OUTSIDE",
    "ERR_VAL_REQ_STRUCT",
    "ERR_VAL_STRUCT_DUMMY_ELEM",
    "ERR_VAL_STRUCT_EMPTY",
    "ERR_VAL_STRUCT_NAN_POS",
    "ERR_VAL_STRUCT_NONE",
    "ERR_VAL_STRUCT_TYPE",
    "ERR_VAL_STRUCT_UNKNOWN_SYM",
    "ERR_VAL_STRUCT_VOL_FAIL",
    "ERR_VAL_STRUCT_ZERO_VOL",
    "ESTIMATED_BYTES_PER_ATOM",
    "FALLBACK_LJ_PARAMS",
    "FILENAME_POTENTIAL",
    "FILE_EXT_EON_POS",
    "FILE_EXT_EXTXYZ",
    "FILE_EXT_XYZ",
    "FILE_NAME_DEPOSITED",
    "FILE_NAME_EON_POS",
    "FILE_NAME_MGO_SURFACE",
    "LAMMPS_MIN_STYLE_CG",
    "LAMMPS_SAFE_CMD_PATTERN",
    "LAMMPS_SCREEN_ARG",
    "MAX_CHUNK_MEM_USAGE_BYTES",
    "MAX_FILE_SIZE_BYTES",
    "MAX_MD_DURATION",
    "MAX_MD_PRESSURE",
    "MAX_PAYLOAD_SIZE_BYTES",
    "PACE_DRIVER_TEMPLATE",
    "PAYLOAD_BASE_OVERHEAD_BYTES",
    "RECIPROCAL_FACTOR",
    "SCENARIO_NAME_FEPT_MGO",
    "TELEMETRY_QUEUE_MAXSIZE",
]

# Telemetry limits
MAX_FILE_SIZE_BYTES = 500_000_000
MAX_PAYLOAD_SIZE_BYTES = 5_000_000
PAYLOAD_BASE_OVERHEAD_BYTES = 100
BYTES_PER_FLOAT64 = 32
BYTES_PER_ATOMIC_NUMBER = 8
TELEMETRY_QUEUE_MAXSIZE = 100
ESTIMATED_BYTES_PER_ATOM = 128
MAX_CHUNK_MEM_USAGE_BYTES = 50_000_000
