from typing import Final

from pyacemaker.domain_models.config import DANGEROUS_PATH_CHARS, DEFAULT_EON_SEED, DEFAULT_MC_SEED

from .defaults import (
        DEFAULT_LAMMPS_MINIMIZE_MAX_ITER,
    DEFAULT_LAMMPS_MINIMIZE_STEPS,
        DEFAULT_LJ_PARAMS,
    DEFAULT_MD_MINIMIZE_FTOL,
    DEFAULT_MD_MINIMIZE_TOL,
    DEFAULT_RAM_DISK_PATH,
    DEFAULT_STRAIN_RANGE,
    EMBEDDING_TOLERANCE_CELL,
    ERR_GEN_BASE_FAIL,
    ERR_GEN_NCAND_NEG,
    ERR_M3GNET_PRED_FAIL,
    ERR_ORACLE_FAILED,
    ERR_ORACLE_ITERATOR,
    ERR_ORACLE_WARN_EMPTY,
    ERR_POTENTIAL_NOT_FOUND,
    ERR_SIM_EXEC_FAIL,
    ERR_SIM_SECURITY_FAIL,
    ERR_SIM_SETUP_FAIL,
    ERR_SIM_UNEXPECTED,
    ERR_STRUCTURE_NONE,
    ERR_VAL_POT_NONE,
    ERR_VAL_POT_NOT_FILE,
    ERR_VAL_POT_OUTSIDE,
    ERR_VAL_REQ_STRUCT,
    ERR_VAL_STRUCT_DUMMY_ELEM,
    ERR_VAL_STRUCT_EMPTY,
    ERR_VAL_STRUCT_NAN_POS,
    ERR_VAL_STRUCT_NONE,
    ERR_VAL_STRUCT_TYPE,
    ERR_VAL_STRUCT_UNKNOWN_SYM,
    ERR_VAL_STRUCT_VOL_FAIL,
    ERR_VAL_STRUCT_ZERO_VOL,
    FALLBACK_LJ_PARAMS,
    LAMMPS_MIN_STYLE_CG,
    LAMMPS_SAFE_CMD_PATTERN,
    LAMMPS_SCREEN_ARG,
    MAX_MD_DURATION,
    MAX_MD_PRESSURE,
    PACE_DRIVER_TEMPLATE,
    RECIPROCAL_FACTOR,
)

# Strategy Constants
STRATEGY_RATTLE_STDEV_INCREASE_FACTOR: Final[float] = 1.1
STRATEGY_RATTLE_STDEV_DECREASE_FACTOR: Final[float] = 0.95
STRATEGY_RATTLE_STDEV_MAX: Final[float] = 0.5
STRATEGY_RATTLE_STDEV_MIN: Final[float] = 0.05

# Policy Constants
POLICY_MICROBURST_N_STEPS: Final[int] = 100
POLICY_MICROBURST_NOISE_STDEV: Final[float] = 0.1
POLICY_NORMALMODE_NOISE_STDEV: Final[float] = 0.05

# Scenario Constants
SCENARIO_NAME_FEPT_MGO: Final[str] = "fept_mgo"
FILE_EXT_XYZ: Final[str] = "xyz"
FILE_EXT_EON_POS: Final[str] = "eon"
FILE_EXT_EXTXYZ: Final[str] = "extxyz"
FILE_NAME_MGO_SURFACE: Final[str] = "mgo_surface.xyz"
FILE_NAME_DEPOSITED: Final[str] = "deposited.xyz"
FILE_NAME_EON_POS: Final[str] = "pos.con"

__all__ = [
    "BYTES_PER_ATOMIC_NUMBER",
    "BYTES_PER_FLOAT64",
    "DANGEROUS_PATH_CHARS",
        "DEFAULT_EON_SEED",
    "DEFAULT_LAMMPS_MINIMIZE_MAX_ITER",
    "DEFAULT_LAMMPS_MINIMIZE_STEPS",
        "DEFAULT_LJ_PARAMS",
    "DEFAULT_MC_SEED",
    "DEFAULT_MD_MINIMIZE_FTOL",
    "DEFAULT_MD_MINIMIZE_TOL",
    "DEFAULT_RAM_DISK_PATH",
    "DEFAULT_STRAIN_RANGE",
    "EMBEDDING_TOLERANCE_CELL",
    "ERR_GEN_BASE_FAIL",
    "ERR_GEN_NCAND_NEG",
    "ERR_M3GNET_PRED_FAIL",
    "ERR_ORACLE_FAILED",
    "ERR_ORACLE_ITERATOR",
    "ERR_ORACLE_WARN_EMPTY",
    "ERR_POTENTIAL_NOT_FOUND",
    "ERR_SIM_EXEC_FAIL",
    "ERR_SIM_SECURITY_FAIL",
    "ERR_SIM_SETUP_FAIL",
    "ERR_SIM_UNEXPECTED",
    "ERR_STRUCTURE_NONE",
    "ERR_VAL_POT_NONE",
    "ERR_VAL_POT_NOT_FILE",
    "ERR_VAL_POT_OUTSIDE",
    "ERR_VAL_REQ_STRUCT",
    "ERR_VAL_STRUCT_DUMMY_ELEM",
    "ERR_VAL_STRUCT_EMPTY",
    "ERR_VAL_STRUCT_NAN_POS",
    "ERR_VAL_STRUCT_NONE",
    "ERR_VAL_STRUCT_TYPE",
    "ERR_VAL_STRUCT_UNKNOWN_SYM",
    "ERR_VAL_STRUCT_VOL_FAIL",
    "ERR_VAL_STRUCT_ZERO_VOL",
    "ESTIMATED_BYTES_PER_ATOM",
    "FALLBACK_LJ_PARAMS",
    "FILE_EXT_EON_POS",
    "FILE_EXT_EXTXYZ",
    "FILE_EXT_XYZ",
    "FILE_NAME_DEPOSITED",
    "FILE_NAME_EON_POS",
    "FILE_NAME_MGO_SURFACE",
    "LAMMPS_MIN_STYLE_CG",
    "LAMMPS_SAFE_CMD_PATTERN",
    "LAMMPS_SCREEN_ARG",
    "MAX_CHUNK_MEM_USAGE_BYTES",
    "MAX_FILE_SIZE_BYTES",
    "MAX_MD_DURATION",
    "MAX_MD_PRESSURE",
    "MAX_PAYLOAD_SIZE_BYTES",
    "PACE_DRIVER_TEMPLATE",
    "PAYLOAD_BASE_OVERHEAD_BYTES",
    "RECIPROCAL_FACTOR",
    "SCENARIO_NAME_FEPT_MGO",
    "TELEMETRY_QUEUE_MAXSIZE",
]

# Telemetry limits
MAX_FILE_SIZE_BYTES = 500_000_000
MAX_PAYLOAD_SIZE_BYTES = 5_000_000
PAYLOAD_BASE_OVERHEAD_BYTES = 100
BYTES_PER_FLOAT64 = 32
BYTES_PER_ATOMIC_NUMBER = 8
TELEMETRY_QUEUE_MAXSIZE = 100
ESTIMATED_BYTES_PER_ATOM = 128
MAX_CHUNK_MEM_USAGE_BYTES = 50_000_000
