from pydantic import BaseModel, ConfigDict, Field, PositiveInt

from pyacemaker.domain_models.defaults import (
    DEFAULT_ACTIVE_LEARNING_DIR,
    DEFAULT_BATCH_SIZE,
    DEFAULT_CHECKPOINT_INTERVAL,
    DEFAULT_DATA_DIR,
    DEFAULT_N_CANDIDATES,
    DEFAULT_OTF_LOCAL_N_CANDIDATES,
    DEFAULT_OTF_LOCAL_N_SELECT,
    DEFAULT_OTF_MAX_RETRIES,
    DEFAULT_OTF_UNCERTAINTY_THRESHOLD,
    DEFAULT_POTENTIALS_DIR,
    DEFAULT_STATE_FILE,
)


class OTFConfig(BaseModel):
    """Configuration for On-The-Fly (OTF) Active Learning loop."""
    model_config = ConfigDict(extra="forbid")

    uncertainty_threshold: float = Field(
        default=DEFAULT_OTF_UNCERTAINTY_THRESHOLD,
        gt=0,
        description="Gamma threshold to trigger halt and retraining."
    )
    local_n_candidates: PositiveInt = Field(
        default=DEFAULT_OTF_LOCAL_N_CANDIDATES,
        description="Number of local candidates to generate around halt structure."
    )
    local_n_select: PositiveInt = Field(
        default=DEFAULT_OTF_LOCAL_N_SELECT,
        description="Number of candidates to select via active set optimization."
    )
    max_retries: PositiveInt = Field(
        default=DEFAULT_OTF_MAX_RETRIES,
        description="Maximum number of retraining attempts per iteration."
    )


class DistillationConfig(BaseModel):
    """Configuration for Phase 1: Zero-Shot Distillation."""
    model_config = ConfigDict(extra="forbid")

    enable: bool = Field(default=False, description="Enable Phase 1 zero-shot distillation.")
    mace_model_path: str = Field(default="MACE-MP-0", description="Path to or name of the MACE model.")
    uncertainty_threshold: float = Field(default=0.05, gt=0, description="MACE uncertainty threshold for retaining structures.")
    sampling_count: PositiveInt = Field(default=1000, description="Number of structures to sample per subsystem via DIRECT sampling.")

class ActiveLearningThresholds(BaseModel):
    """Two-tier thresholds for On-The-Fly Active Learning loop."""
    model_config = ConfigDict(extra="forbid")

    threshold_call_dft: float = Field(default=0.05, gt=0, description="Threshold to pause MD and trigger DFT.")
    threshold_add_train: float = Field(default=0.02, gt=0, description="Threshold to determine 'epicentre' atoms for training.")
    smooth_steps: PositiveInt = Field(default=3, description="Number of consecutive steps required to exceed threshold to trigger a halt (filters thermal noise).")

class CutoutConfig(BaseModel):
    """Configuration for Phase 3: Intelligent Cutout and Passivation."""
    model_config = ConfigDict(extra="forbid")

    core_radius: float = Field(default=3.0, gt=0, description="Radius in Angstroms where force_weight = 1.0")
    buffer_radius: float = Field(default=2.0, ge=0, description="Additional radius in Angstroms where force_weight = 0.0")
    pre_relax: bool = Field(default=True, description="Whether to pre-relax the buffer using MACE while freezing the core.")
    passivation: bool = Field(default=True, description="Whether to automatically passivate broken bonds with dummy atoms.")

class LoopStrategyConfig(BaseModel):
    """Configuration for the Active Learning loop strategies."""
    model_config = ConfigDict(extra="forbid")

    use_tiered_oracle: bool = Field(default=True, description="Use TieredOracle for DFT query minimization.")
    incremental_update: bool = Field(default=True, description="Use delta learning incremental updates to prevent catastrophic forgetting.")
    replay_buffer_size: PositiveInt = Field(default=500, description="Number of historical structures to mix in during training.")
    surrogate_data_count: PositiveInt = Field(default=1000, description="Number of surrogate structures generated by awakened MACE.")


class WorkflowConfig(BaseModel):
    model_config = ConfigDict(extra="forbid")

    max_iterations: PositiveInt = Field(..., description="Maximum number of active learning cycles")
    convergence_energy: float = Field(
        default=0.001, gt=0, description="Energy convergence criteria in eV/atom"
    )
    convergence_force: float = Field(
        default=0.01, gt=0, description="Force convergence criteria in eV/Angstrom"
    )
    state_file_path: str = Field(
        default=DEFAULT_STATE_FILE, description="Path to the state checkpoint file"
    )

    # New fields to avoid magic numbers
    batch_size: PositiveInt = Field(
        default=DEFAULT_BATCH_SIZE, description="Number of structures to process in a batch"
    )
    n_candidates: PositiveInt = Field(
        default=DEFAULT_N_CANDIDATES,
        description="Number of candidate structures to generate per iteration",
    )
    checkpoint_interval: PositiveInt = Field(
        default=DEFAULT_CHECKPOINT_INTERVAL, gt=0, description="Save state every N iterations"
    )
    data_dir: str = Field(
        default=DEFAULT_DATA_DIR, description="Directory to store training data and artifacts"
    )
    active_learning_dir: str = Field(
        default=DEFAULT_ACTIVE_LEARNING_DIR, description="Directory for active learning iterations"
    )
    potentials_dir: str = Field(
        default=DEFAULT_POTENTIALS_DIR, description="Directory for storing trained potentials"
    )

    otf: OTFConfig = Field(
        default_factory=OTFConfig,
        description="Configuration for OTF loop."
    )
    distillation: DistillationConfig = Field(
        default_factory=DistillationConfig,
        description="Settings for Phase 1 distillation."
    )
    thresholds: ActiveLearningThresholds = Field(
        default_factory=ActiveLearningThresholds,
        description="Two-tier thresholds for thermal noise tolerance."
    )
    cutout: CutoutConfig = Field(
        default_factory=CutoutConfig,
        description="Settings for intelligent cluster extraction."
    )
    loop_strategy: LoopStrategyConfig = Field(
        default_factory=LoopStrategyConfig,
        description="Strategy settings for incremental update and tiered oracle."
    )
