import ase
import numpy as np
import pytest
from ase.build import bulk

from pyacemaker.domain_models.scenario import SpatialAction, SpatialRegion
from pyacemaker.utils.spatial import apply_spatial_tags


@pytest.fixture
def test_structure() -> "ase.Atoms":
    """Create a 10x10x10 simple cubic lattice of Copper."""
    atoms = bulk("Cu", "sc", a=1.0, cubic=True)
    return atoms * (10, 10, 10)  # Total 1000 atoms


def test_apply_spatial_tags_basic(test_structure) -> None:
    # The structure generated by bulk * (10,10,10) has positions from 0.0 to 9.0.
    # We want Z < 5.0 (0, 1, 2, 3, 4 -> 500 atoms). But we must use -0.1 to include 0.0 safely.
    region = SpatialRegion(
        x_min=-1.0,
        x_max=11.0,
        y_min=-1.0,
        y_max=11.0,
        z_min=-0.1,
        z_max=4.5,
        action=SpatialAction.ACTION_FREEZE,
    )

    tags = apply_spatial_tags(test_structure, [region])

    assert tags.shape == (1000,)
    assert np.sum(tags == 1) == 500
    assert np.sum(tags == 0) == 500


def test_apply_spatial_tags_inclusive_exclusive(test_structure) -> None:
    region = SpatialRegion(
        x_min=-1.0,
        x_max=11.0,
        y_min=-1.0,
        y_max=11.0,
        z_min=4.9,
        z_max=5.5,
        action=SpatialAction.ACTION_FREEZE,
    )

    tags = apply_spatial_tags(test_structure, [region])

    # 10x10 = 100 atoms on a single plane
    assert np.sum(tags == 1) == 100


def test_apply_spatial_tags_overlap_resolution(test_structure) -> None:
    # Two overlapping regions
    # Region 1 (FREEZE - high priority) from Z=0 to Z < 5 (Z=0,1,2,3,4 -> 500 atoms)
    reg1 = SpatialRegion(
        x_min=-1.0,
        x_max=11.0,
        y_min=-1.0,
        y_max=11.0,
        z_min=-0.1,
        z_max=4.5,
        action=SpatialAction.ACTION_FREEZE,
    )
    # Region 2 (THERMOSTAT - lower priority) from Z=3 to Z < 8 (Z=3,4,5,6,7 -> 500 atoms)
    reg2 = SpatialRegion(
        x_min=-1.0,
        x_max=11.0,
        y_min=-1.0,
        y_max=11.0,
        z_min=2.5,
        z_max=7.5,
        action=SpatialAction.ACTION_LANGEVIN_THERMOSTAT,
    )

    tags = apply_spatial_tags(test_structure, [reg1, reg2])

    # Z=0,1,2,3,4 -> FREEZE (tags=1) => 500 atoms. Even though 3,4 overlap with reg2, reg1 has higher priority.
    # Z=5,6,7 -> THERMOSTAT (tags=2) => 300 atoms.
    # Z=8,9 -> None (tags=0) => 200 atoms.

    assert np.sum(tags == 1) == 500
    assert np.sum(tags == 2) == 300
    assert np.sum(tags == 0) == 200


def test_apply_spatial_tags_unresolvable_conflict(test_structure) -> None:
    reg1 = SpatialRegion(
        x_min=-1.0,
        x_max=11.0,
        y_min=-1.0,
        y_max=11.0,
        z_min=0.0,
        z_max=5.0,
        action=SpatialAction.ACTION_LANGEVIN_THERMOSTAT,
    )
    reg2 = SpatialRegion(
        x_min=-1.0,
        x_max=11.0,
        y_min=-1.0,
        y_max=11.0,
        z_min=3.0,
        z_max=8.0,
        action=SpatialAction.ACTION_LANGEVIN_THERMOSTAT,
    )

    with pytest.raises(ValueError, match="Unresolvable spatial region conflict"):
        apply_spatial_tags(test_structure, [reg1, reg2])


def test_apply_spatial_tags_empty_selection(test_structure) -> None:
    # Region completely outside the structure
    reg1 = SpatialRegion(
        x_min=100.0,
        x_max=110.0,
        y_min=100.0,
        y_max=110.0,
        z_min=100.0,
        z_max=110.0,
        action=SpatialAction.ACTION_FREEZE,
    )

    tags = apply_spatial_tags(test_structure, [reg1])
    assert np.sum(tags == 0) == 1000
    assert np.sum(tags == 1) == 0


def test_apply_spatial_tags_active_learning(test_structure) -> None:
    reg1 = SpatialRegion(
        x_min=-1.0,
        x_max=11.0,
        y_min=-1.0,
        y_max=11.0,
        z_min=-0.1,
        z_max=4.5,
        action=SpatialAction.ACTION_ACTIVE_LEARNING_ONLY,
    )

    tags = apply_spatial_tags(test_structure, [reg1])

    assert tags.shape == (1000,)
    assert np.sum(tags == 1) == 500
