# Logging Messages
LOG_PROJECT_INIT = "Project: {project_name} initialized."
LOG_CONFIG_LOADED = "Configuration loaded successfully."
LOG_DRY_RUN_COMPLETE = "Dry run complete. Exiting."
LOG_INIT_MODULES = "Initializing modules..."
LOG_MODULES_INIT_SUCCESS = "Modules initialized (Mock mode for Cycle 01)."
LOG_MODULE_INIT_FAIL = "Failed to initialize modules: {error}"
LOG_START_LOOP = "Starting active learning loop."
LOG_START_ITERATION = "Starting Iteration {iteration}/{max_iterations}"
LOG_GENERATED_CANDIDATES = "Generated {count} candidates"
LOG_COMPUTED_PROPERTIES = "Computed properties for {count} structures"
LOG_POTENTIAL_TRAINED = "Potential trained"
LOG_MD_COMPLETED = "MD simulation completed"
LOG_ITERATION_COMPLETED = "Iteration {iteration} completed."
LOG_WORKFLOW_COMPLETED = "Workflow completed."
LOG_WORKFLOW_CRASHED = "Workflow crashed: {error}"
LOG_STATE_SAVED = "State saved: {state}"
LOG_STATE_SAVE_FAIL = "Failed to save state: {error}"
LOG_STATE_LOAD_SUCCESS = "Resuming from iteration {iteration}"
LOG_STATE_LOAD_FAIL = "Failed to load state, starting fresh: {error}"

# Error Messages
ERR_CONFIG_NOT_FOUND = "Configuration file not found: {path}"
ERR_PATH_NOT_FILE = "Path is not a file: {path}"
ERR_YAML_PARSE = "Error parsing YAML file: {error}"
ERR_YAML_NOT_DICT = "YAML file must contain a dictionary"
ERR_PATH_TRAVERSAL = "Path traversal detected: {path} is outside allowed directory {base}"
ERR_MODULE_INIT = "Module initialization failed: {error}"

# Path Templates & Constants
TEMPLATE_ITER_DIR = "iter_{iteration:03d}"
TEMPLATE_POTENTIAL_FILE = "generation_{iteration:03d}.yace"
FILENAME_CANDIDATES = "candidates.xyz"
FILENAME_TRAINING = "training_data.xyz"
